stages:
  preprocess:
    cmd: python src/preprocess.py data/scorecards.csv data/course_registry.csv data/processed_scores.csv
    deps:
      - src/preprocess.py
      - data/scorecards.csv
      - data/course_registry.csv
    outs:
      - data/processed_scores.csv
  train:
    cmd: python src/train.py data/processed_scores.csv models/model.pkl
    deps:
      - src/train.py
      - data/processed_scores.csv
    outs:
      - models/model.pkl
