name: MLOps CI
on: [push]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 src/
      - name: Run unit tests
        env:
          PYTHONPATH: .
        run: python -m pytest